name: http_api_helper
description: Dart package for simplified API integration and HTTP requests in Flutter projects.
version: 0.1.0
repository: https://github.com/RashminDungrani/http_api_helper

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.0.0
  dartz: ^0.10.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
